### ISSUE TITLE
[GREENFOOT-696] Update Copyright dialog.

### ISSUE THREAD

**Issue by neilccbrown** [k-pet-group/BlueJ-Greenfoot#2030]
In GitLab by @amjad on May 3, 2018, 15:48

---

**Issue metadata**

- Issue type: Bug
- Priority: Medium
- Fix versions: 3.5.0

**Comment by koppor** [comment]
Again relevant for 2025 - because the year is 2022 in the current dialog. Should I open a new issue?

<img width="561" height="310" alt="Image" src="https://github.com/user-attachments/assets/8f9cbbf8-a19e-4e9b-b35e-295d79556211" />
