### ISSUE TITLE
Cannot open more than one project at a time with BlueJ 5.1.0a on MacOS Ventura 13.0 - by double-click

### ISSUE THREAD

**Issue by astyve** [k-pet-group/BlueJ-Greenfoot#2204]
After upgrading to 5.1 of BlueJ, I can no longer open more than one project at a time. If BlueJ is open with a project, and I double-click another project file, the other project is not opened. Instead the current open project gets focus.
Opening an additional project from "File->Open" works fine, so the problem probably lies in the double-click action in the MacOS?

**Comment by neilccbrown** [comment]
This is part of #2190 which has now been fixed for the upcoming release.
