### ISSUE TITLE
BlueJ 5.0 fails to launch on Mac Ventura

### ISSUE THREAD

**Issue by sethrun49** [k-pet-group/BlueJ-Greenfoot#2214]
BlueJ fails to launch.  Running MacOS Ventura 13.1
<img width="2048" alt="Screenshot 2023-01-25 at 1 42 26 PM" src="https://user-images.githubusercontent.com/123588533/214656425-90bf3e65-ec4a-43f3-8280-e9062561f6bc.png">

**Comment by neilccbrown** [comment]
This is probably the bug where 5.1.0 and earlier crashed on Ventura.  It is solved in version 5.1.0a, which is available for download on our main page: https://www.bluej.org/
