### ISSUE TITLE
Projects don't open when package.bluej is double-clicked, or opened from the command line.

### ISSUE THREAD

**Issue by WmHHooper** [k-pet-group/BlueJ-Greenfoot#2215]
The problem is worse than issue [BLUEJ-921], which was closed last October.  When package.bluej is opened, BlueJ launches if it's not active, but I have to choose **Open Project...** from the **Project** menu and navigate to the folder to open it.  If BlueJ is already running, opening  package.bluej does not seem to have any effect.  The problem persists whether I double-click the package.bluej icon, or execute `open path/to/package.bluej` from the command line.

I'm running BlueJ 5.10a in MacOS Ventura 13.1 (22C65) on a 13-inch MacBook Pro, made in 2018.

**Comment by neilccbrown** [comment]
This is part of #2190 which has now been fixed for the upcoming release.
