### ISSUE TITLE
The application requires 10.12 and not 10.11 as indicated on the page

### ISSUE THREAD

**Issue by MacTerrassa** [k-pet-group/BlueJ-Greenfoot#2235]
Only notify that the downloaded application comes with the forbidden symbol since it has been compiled for 10.12 or higher. Anyway, I understand that it requires Java 17 which also requires a post 10.11 system already. And anyway, for years now none of the BlueJ versions have worked for me on my mac, I am only able to open a very old 4.0.1. All subsequent ones either hang or generate a missing library error message.
Has it worked for everyone so far? I understand that things have changed now, but have they really worked all this time or is it just that everyone just assumes that everything always requires the latest version of everything?

**Comment by neilccbrown** [comment]
Thanks, we will correct the webpage.  As far as we know, 10.11 was the requirement until 5.2.0, although we don't always have an old Mac to test on.  What is your macOS version?

**Comment by MacTerrassa** [comment]
Hello, I use precisely 10.11 on a 2007 iMac, is it possible that my problem is due to the chip and not exactly due to the system? I understand that some program that claimed to be compatible with 10.11, in its technical support blamed the chip and its lack of support for certain orders for not working.
P.S. mechanically translated message since I do not speak English I apologize if I have not expressed myself correctly.

**Comment by neilccbrown** [comment]
As far as I can tell, the 2007 iMac did have a 64-bit CPU so in theory may work, but in reality that's 16 years old so it would not be surprising if Java no longer supported that CPU.  If you get a specific error message then you could provide that here.

**Comment by neilccbrown** [comment]
Website updated (5.4.1 and possibly 5.4.0 require macOS 11).  The minimum dependency is usually determined by the JDK so there's not much we can do to support older versions except to use an older BlueJ.

**Comment by MacTerrassa** [comment]
Just tell you that at least since version 5.2.0 BlueJ requires at least 10.12 Sierra, since the JDK version requires it. I haven't been able to review previous versions yet, but perhaps the error with my old iMac and 10.11 system came from that side. Although I understand that they do not offer new versions for old systems, it seems correct to indicate any changes in those requirements. That way, if someone needs to use BlueJ (or any program) on an obsolete system, they can determine which version will work, and we don't bother the forums for issues so easy to solve :-)
