### ISSUE TITLE
Add more specific error message when trying to access http repositories

### ISSUE THREAD

**Issue by chriswainformatik** [k-pet-group/BlueJ-Greenfoot#2306]
I set up a private git server and forgot to enable https. I tested the server using git on the command line and I could push changes to repositories. I then entered my credentials in BlueJ and tested the connection successfully. But each time I tried to get the repo status/pull/push I got the error message

`<my-repo-uri>: Authentication is required but no CredentialsProvider has been registered.`

While not enabling https was my own fault, a meaningful error message would have helped me find the issue a lot quicker.

So my suggestion is to add a more specific error message when trying to access repositories over http instead of https. I would think it also a good option to fail the connection test in this case instead of succeeding.

**Comment by neilccbrown** [comment]
This error is passed through from the jgit library that we use to handle Git.  Although I agree it's unhelpful, I'm not sure it's so feasible to introduce mapping their errors into better errors ourselves, as that error probably covers other cases than http/https.  You could try filing an issue with them to suggest a better error for this case: https://github.com/eclipse-jgit/jgit/issues

Although, I'm not happy that the connection tested successfully and then didn't work for a subsequent status check with the same settings; that should not happen.  Do you have any way that we could replicate this problem ourselves to look into it?

**Comment by chriswainformatik** [comment]
What I did on my server was:
- set up an apache webserver
- set up gitea
- add a virtual host for gitea
- do not set up https for that virtual host
- try to create a repository on that gitea instance via BlueJ
- try to checkout an existing repository on that gitea instance in BlueJ

**Comment by chriswainformatik** [comment]
So I posted the issue in the jgit repository forum and they said that this actually is a BlueJ issue: [https://github.com/eclipse-jgit/jgit/issues/18](https://github.com/eclipse-jgit/jgit/issues/18)

On top of that they described a few bugs in the BlueJ implementation (see linked topic).

**Comment by neilccbrown** [comment]
Apologies that I informed you wrongly!  I'm not very familiar with the Git code as it was written by team members who've since left but I'll look into the bugs they mention.  Thanks for following it up.
