### ISSUE TITLE
Flatpak is outdated

### ISSUE THREAD

**Issue by chr-lw** [k-pet-group/BlueJ-Greenfoot#2381]
Hello.
Could you update the flatpak on FlatHub? It is currently at version 5.2.1.
Thanks :)

**Comment by neilccbrown** [comment]
The flatpak is not produced by us; you will need to contact the maintainer of the flatpak.  I'm not sure who that is but I think this repository might be related (I'm not very familiar with flatpak): https://github.com/flathub/org.bluej.BlueJ

**Comment by chr-lw** [comment]
Sorry, I thought it was maintained by you, because they link to this repo on Flathub. I will try the other repo. Thanks :)
