### ISSUE TITLE
Not a bug question but need help

### ISSUE THREAD

**Issue by pheonixfirewingz** [k-pet-group/BlueJ-Greenfoot#2402]
How do i get bluej v4.1.4 to register txt files i made in my project externally? It’s driving be nuts. I have to use v4.1.4 due to my university requirements.

**Comment by neilccbrown** [comment]
BlueJ only started supporting editing arbitrary text files in version 5.0.1, so it isn't possible.  The only work-arounds are that BlueJ 4.1.4 did support editing README.txt, and I believe it also supported editing CSS files so if you renamed the extension to .css they should show up and be editable.  You can decide if that works for you or not.
