### ISSUE TITLE
FTBFS: BlueJ-Greenfoot-BLUEJ-RELEASE-5.4.1.tar.gz fails to build from source

### ISSUE THREAD

**Issue by tassia** [k-pet-group/BlueJ-Greenfoot#2417]
It seems the build relies on the presence of a git repository, which is removed from the released tar.gz.

I've fixed the issue by editing the file bluej/build.gradle, and commenting the line 106: 
`//copyToLib.dependsOn recordCommitID`

Here is the record of my failed build:

```
$ ./gradlew runBlueJ

> Task :bluej:recordCommitID FAILED
fatal: not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bluej:recordCommitID'.
> Process 'command 'git'' finished with non-zero exit value 128

```

**Comment by neilccbrown** [comment]
Thanks for pointing this out; I'd forgotten that users might build from the source zip rather than cloning when I added in the code to pick out the Git hash.
